config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'cocktails', to: 'cocktails#index', as: 'cocktails'
  get 'cocktails/new', to: 'cocktails#new', as: 'new_cocktail'
  get 'cocktails/:id', to: 'cocktails#show', as: 'cocktail'
  post 'cocktails', to: 'cocktails#create'

  get 'cocktails/:cocktail_id/doses/new', to: 'doses#new', as: 'new_dose'
  post 'cocktails/:cocktail_id/doses', to: 'doses#create', as: 'cocktail_doses'
  delete 'doses/:id', to: 'doses#destroy', as: 'dose'

  # This (below)is the shorthand way to do the lines above

  # resources :cocktails, only: [:index, :new, :show,:create] do
  #     resources :doses, only: [:new, :create]
  #   end
  #   resources :doses, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses

  validates :name, uniqueness: true, presence: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :ingredient
  belongs_to :cocktail

  validates :description, presence: true
  validates_uniqueness_of :ingredient_id, :scope => :cocktail_id
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses

  validates :name, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_params, only: :show
  def index
    @cocktails = Cocktail.all.sort_by { |cocktail| cocktail.name }
  end

  def show
    @doses = @cocktail.doses
    @ingredients = @cocktail.ingredients
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name)
  end

  def set_params
    @cocktail = Cocktail.find(params[:id])
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :set_cocktail, only: [:new, :create]

  def new
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail.id)
    else
      render 'new'
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @cocktail = @dose.cocktail
    @dose.destroy
    redirect_to cocktail_path(@cocktail)
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.1),rgba(0,0,0,0.6)), url(https://images.unsplash.com/photo-1509807995916-c332365e2d9e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1571&q=80);">
  <div class="headder">
    <h1>Feeling Thirsty?</h1>
    <p>You've come to the right place.</p>
    <%= link_to "Get Creative", new_cocktail_path, class: "btn btn-ghost" %>
  </div>
</div>



<div class="container">
  <div class="cards">

      <% @cocktails.each do |cocktail| %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://loremflickr.com/320/240/drink,cocktail)">
          <%= link_to cocktail.name, cocktail_path(cocktail), class: "drink-link" %>
        </div>
      <% end %>
  </div>
</div>

app/views/cocktails/new.html.erb
<h1>Create a New Cocktail</h1>


<%= simple_form_for @cocktail do |f| %>
  <%= f.input :name %>
  <%= f.button :submit %>
<% end %>

app/views/cocktails/show.html.erb
<div class="headder"><h2>  <%= @cocktail.name %> </h2> </div>

<div class="show-body">
  <div class="left-side">
    <img src="https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=400&q=60" alt="">
  </div>


  <div class="right-side">
    <% @doses.each do |dose| %>
    <%= dose.description %> <%= dose.ingredient.name %>
    <%= link_to "Delete this Dose", dose_path(dose), method: :delete  %>
    <% end %>
  </div>

  <%= link_to "Add a Dose to this Cocktail", new_dose_path(@cocktail) %>
  <%= link_to "List of all drinks", cocktails_path  %>
</div>

app/views/doses/new.html.erb
<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.input :description %>
  <%= f.association :ingredient %>
  <%= f.button :submit %>
<% end %>
<%= link_to "back", cocktail_path(@cocktail) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Raleway:100,200,400,500&display=swap" rel="stylesheet">
  </head>

  <body>
    <%= yield %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
    <%= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->
  </body>
</html>